csk/urls.py
from django.urls import path
from csk.views import *
app_name='csk'
urlpatterns=[
    path('csk/',csk,name='csk')
]

rcb/urls.py
from django.urls import path
from rcb.views import *
app_name='rcb'
urlpatterns=[
    path('rcb/',rcb,name='rcb')
]

specific_url_mapping/urls.py
from django.contrib import admin
from django.urls import path,include
import csk,rcb
from csk.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('new/',new,name='new'),
    path('csk/',include('csk.urls')),
    path('rcb/',include('rcb.urls'))
]

csk/models.py
from django.db import models

# Create your models here.

rcb/models.py
from django.db import models

# Create your models here.

csk/views.py
from django.shortcuts import render

# Create your views here.
def csk(request):
    return render(request,'csk.html')
def new(request):
    return render(request,'new.html')

rcb/views.py
from django.shortcuts import render

# Create your views here.
def rcb(request):
    return render(request,'rcb.html')

templates/csk.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>csk-dhoni</title>
</head>
<body>
    <center>
        <h1>csk html page</h1>
        <h1><a href="{% url 'rcb:rcb' %}">go to rcb </a></h1>
        <h1><a href="{% url 'new' %}">go to new page</a></h1>
    </center>
</body>
</html>

templates/new.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>just for </title>
</head>
<body>
    <center>
        <h1>just for connecting html pages</h1>
        <h1><a href="{% url 'rcb:rcb' %}">go to rcb</a></h1>
        <h1><a href="{% url 'csk:csk' %}">to connect csk</a></h1>
    </center>
</body>
</html>

templates/rcb.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>RCB</title>
</head>
<body>
    <center>
        <h1>RCB HTML Page is created</h1>
        <h1><a href="{% url 'csk:csk' %}">go to csk</a></h1>
    </center>
</body>
</html>